import type { Project, Task, User } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    orgId: "org1",
    name: "Sarah L.",
    initials: "SL",
    email: "sarah@org.com",
    role: "Lead",
    loadLevel: "at_capacity",
    taskCount: 8,
    loadPercent: 85,
  },
  {
    id: "u2",
    orgId: "org1",
    name: "Aiden K.",
    initials: "AK",
    email: "aiden@org.com",
    role: "Dev",
    loadLevel: "overloaded",
    taskCount: 12,
    loadPercent: 130,
  },
  {
    id: "u3",
    orgId: "org1",
    name: "Meera P.",
    initials: "MP",
    email: "meera@org.com",
    role: "Design",
    loadLevel: "available",
    taskCount: 3,
    loadPercent: 40,
  },
  {
    id: "u4",
    orgId: "org1",
    name: "Luca R.",
    initials: "LR",
    email: "luca@org.com",
    role: "Dev",
    loadLevel: "available",
    taskCount: 4,
    loadPercent: 55,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    orgId: "org1",
    name: "Annual Hackathon",
    color: "coral",
    status: "active",
    ownerId: "u1",
    completionPercent: 62,
    startDate: new Date("2026-04-01"),
    endDate: new Date("2026-06-30"),
    phases: [
      {
        id: "ph1",
        projectId: "p1",
        name: "Planning",
        orderIndex: 0,
        completionPercent: 100,
        taskCount: 4,
        doneCount: 4,
      },
      {
        id: "ph2",
        projectId: "p1",
        name: "Build Sprint",
        orderIndex: 1,
        completionPercent: 60,
        taskCount: 5,
        doneCount: 3,
      },
      {
        id: "ph3",
        projectId: "p1",
        name: "Demo Day",
        orderIndex: 2,
        completionPercent: 0,
        taskCount: 3,
        doneCount: 0,
      },
    ],
    members: ["u1", "u2", "u3"],
  },
  {
    id: "p2",
    orgId: "org1",
    name: "Platform Redesign",
    color: "violet",
    status: "active",
    ownerId: "u3",
    completionPercent: 30,
    startDate: new Date("2026-03-15"),
    endDate: new Date("2026-08-15"),
    phases: [
      {
        id: "ph4",
        projectId: "p2",
        name: "Research",
        orderIndex: 0,
        completionPercent: 100,
        taskCount: 3,
        doneCount: 3,
      },
      {
        id: "ph5",
        projectId: "p2",
        name: "Design System",
        orderIndex: 1,
        completionPercent: 40,
        taskCount: 5,
        doneCount: 2,
      },
    ],
    members: ["u3", "u4"],
  },
  {
    id: "p3",
    orgId: "org1",
    name: "Data Pipeline",
    color: "sky",
    status: "planning",
    ownerId: "u2",
    completionPercent: 10,
    startDate: new Date("2026-05-01"),
    endDate: new Date("2026-09-01"),
    phases: [
      {
        id: "ph6",
        projectId: "p3",
        name: "Architecture",
        orderIndex: 0,
        completionPercent: 30,
        taskCount: 4,
        doneCount: 1,
      },
    ],
    members: ["u2", "u4"],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    phaseId: "ph2",
    projectId: "p1",
    title: "Auth system setup",
    status: "done",
    priority: "critical",
    assigneeIds: ["u2"],
    effortEstimate: 8,
    canvasX: 300,
    canvasY: 150,
    isCriticalPath: true,
    slackTime: 0,
    dependencies: [],
    dependents: ["t2", "t3"],
  },
  {
    id: "t2",
    phaseId: "ph2",
    projectId: "p1",
    title: "Canvas engine mount",
    status: "in_progress",
    priority: "critical",
    assigneeIds: ["u1", "u2"],
    effortEstimate: 12,
    canvasX: 580,
    canvasY: 80,
    isCriticalPath: true,
    slackTime: 0,
    dependencies: ["t1"],
    dependents: ["t5"],
    description:
      "Mount ReactFlow with all custom nodes and semantic zoom",
  },
  {
    id: "t3",
    phaseId: "ph2",
    projectId: "p1",
    title: "Design token audit",
    status: "in_review",
    priority: "high",
    assigneeIds: ["u3"],
    effortEstimate: 4,
    canvasX: 580,
    canvasY: 240,
    isCriticalPath: false,
    slackTime: 3,
    dependencies: ["t1"],
    dependents: ["t4"],
    dueDate: new Date("2026-06-10"),
  },
  {
    id: "t4",
    phaseId: "ph2",
    projectId: "p1",
    title: "Component library",
    status: "blocked",
    priority: "high",
    assigneeIds: ["u3"],
    effortEstimate: 16,
    canvasX: 860,
    canvasY: 240,
    isCriticalPath: false,
    slackTime: 3,
    dependencies: ["t3"],
    dependents: ["t5"],
  },
  {
    id: "t5",
    phaseId: "ph3",
    projectId: "p1",
    title: "Demo presentation",
    status: "not_started",
    priority: "critical",
    assigneeIds: ["u1"],
    effortEstimate: 6,
    canvasX: 1140,
    canvasY: 150,
    isCriticalPath: true,
    slackTime: 0,
    dependencies: ["t2", "t4"],
    dependents: [],
    dueDate: new Date("2026-06-28"),
  },
  {
    id: "t6",
    phaseId: "ph5",
    projectId: "p2",
    title: "Color system design",
    status: "in_progress",
    priority: "high",
    assigneeIds: ["u3"],
    effortEstimate: 8,
    canvasX: 300,
    canvasY: 520,
    isCriticalPath: true,
    slackTime: 0,
    dependencies: [],
    dependents: ["t7"],
  },
  {
    id: "t7",
    phaseId: "ph5",
    projectId: "p2",
    title: "Component specs",
    status: "not_started",
    priority: "medium",
    assigneeIds: ["u4"],
    effortEstimate: 12,
    canvasX: 580,
    canvasY: 520,
    isCriticalPath: false,
    slackTime: 5,
    dependencies: ["t6"],
    dependents: [],
  },
  {
    id: "t8",
    phaseId: "ph6",
    projectId: "p3",
    title: "Schema definition",
    status: "in_progress",
    priority: "high",
    assigneeIds: ["u2"],
    effortEstimate: 6,
    canvasX: 300,
    canvasY: 820,
    isCriticalPath: true,
    slackTime: 0,
    dependencies: [],
    dependents: ["t9"],
  },
  {
    id: "t9",
    phaseId: "ph6",
    projectId: "p3",
    title: "Ingestion pipeline",
    status: "not_started",
    priority: "critical",
    assigneeIds: ["u2", "u4"],
    effortEstimate: 20,
    canvasX: 580,
    canvasY: 820,
    isCriticalPath: true,
    slackTime: 0,
    dependencies: ["t8"],
    dependents: [],
  },
];

export const USER_MAP: Record<string, User> = Object.fromEntries(
  MOCK_USERS.map((u) => [u.id, u]),
);
